---
- hosts: databases
  tasks:
  - name: create file if it doesn't exist
    file:
      state: touch
      path: /home/ansible/hostname.conf
  - name: If line is not there, add it.
    lineinfile:
      state: present
      dest: /home/ansible/hostname.conf
      line: Hostname={{ansible_hostname}} 
