---
- hosts: databases
  tasks:
   - name: pring stdout
     command: echo "Testing, hello"
     register: hello
   - debug: msg="stdout={{ hello.stdout }}"
   - debug: msg="stderr={{ hello.stderr }}"
   - debug:
      msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
