---
- hosts: databases
  tasks:
    - name: copy file to server
      copy: src=test.sh dest=/home/ansible/test.sh mode=0755
    - name: run the script
      command: /home/ansible/test.sh
      register: output_vale
      ignore_errors: yes
    - debug:
       msg="STDOUT - {{ output_vale.stdout }}"
    - debug:
       msg="STDERR - {{ output_vale.stderr }}"
  
