---
- hosts: databases
  become: yes
  tasks:
   - name: Install mysql server
     yum: name=mysql-server state=latest
     ignore_errors: yes
     register: its_there
   - name: Start mysql
     service: name=mysqld state=started
     register: its_running
