---
- hosts: databases
  tasks:
     - shell: cat /etc/motd
       register: motd_contents
     - debug: msg="stdout={{motd_contents}}"
     - debug: msg="MOTD IS EMPTY"
       when: motd_contents.stdout == ""
